### ISSUE TITLE
Should PlTracks just be Songs?

### ISSUE THREAD

**Issue by rfilmyer** [liamks/pyitunes#17]
Is there a reason that a Playlist is a list of PlTracks, rather than a list of Songs?

It looks like a PlTrack just pulls a few select attributes from the corresponding Song referenced by a Playlist, but you can't convert a PlTrack to a dict the way you can with a Song.

There might be a technical reason, but otherwise if I were to compile a list of dicts of all the tracks in a playlist, I would have to reinvent the wheel by going back to the original XML and getting track IDs, looking them up.

**Comment by mbramson** [comment]
That's a great point. I think that playlists should be lists of song objects. Makes a lot more sense.

**Comment by rfilmyer** [comment]
I'll submit a pull request this week

**Comment by liamks** [comment]
Sounds like a great idea - thanks @rfilmyer!

**Comment by rfilmyer** [comment]
Well isn't that classic.
At least I made the change today in my fork. With my change, playlists are now composed of `Song`s with an additional `self.number` property, corresponding to their location in the playlist.

For a class with `self.track_number` and `self.disc_number`, "number" might be a bad choice, but we have to choose whether to break backwards compatibility with old `PlTrack` objects or having a bad variable name.

**Comment by liamks** [comment]
Why not add `order` to denote their location in the playlist. Or even `playlist_order`?

**Comment by rfilmyer** [comment]
Good idea. I just wasn't sure whether to do a breaking change or keep a
possibly confusing name.

I'll do `playlist_order` then.

**Comment by shacker** [comment]
`playlist_order` now exists on songs pulled from playlists. Closing.
