### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by erikdhansen** [liamks/pyitunes#25]
Running into very simple problem causing the sample program in the read me to fail.  Song.number is never populated.  In fact, it doesn't even exist in the Song.py class.  I added a couple lines (to Library.py and Song.py) that took care of this and fixed it...

Library.py
```
diff --git a/pyItunes/Library.py b/pyItunes/Library.py
index 60bb75b..2b91266 100644
--- a/pyItunes/Library.py
+++ b/pyItunes/Library.py
@@ -37,6 +37,7 @@ class Library:
                format = "%Y-%m-%d %H:%M:%S"
                for trackid,attributes in self.il['Tracks'].items():
                        s = Song()
+                       s.number = int(trackid)
                        s.name = attributes.get('Name')
                        s.artist = attributes.get('Artist')
                        s.album_artist = attributes.get('Album Artist')
```
and
Song.py
```
diff --git a/pyItunes/Song.py b/pyItunes/Song.py
index e6f00a2..4dc605e 100644
--- a/pyItunes/Song.py
+++ b/pyItunes/Song.py
@@ -2,6 +2,7 @@ class Song:
        """
        Song Attributes:
        name (String)
+       number (Integer)
        artist (String)
        album_artist (String)
        composer = None (String)
@@ -32,6 +33,7 @@ class Song:
        length = None (Integer)
        """
        name = None
+       number = None
        artist = None
        album_artist = None
        composer = None
```

**Comment by liamks** [comment]
I wonder if `Song.number` was removed in a new version of iTunes? Can you double check all the keys associated with each song? Maybe they've renamed it. The solution above assumes that the order of iteration equals song number (not sure this is the case).

**Comment by erikdhansen** [comment]
There is a key called "Track ID" but no key called number in my iTunes Library XML file.  That key (Track ID) in the dictionary entry for the song is the same value as the dictionary entry's key in that dictionary.

- EDH via Overlord

**Comment by liamks** [comment]
Ok, can you use `Track Id` then? I'll happily accept a pull request!

**Comment by erikdhansen** [comment]
You bet — I’ll modify my original change and test it and then do a pull request

**Comment by erikdhansen** [comment]
Actually, do you have an  "iTunes Music Library.xml" file that used to work?  I'd like to make sure that any change can handle either version ;-)  -- maybe consider adding a folder to the root of the project and throwing a couple library XML files in there...would be a good place to proxy track library.xml schema changes, anyway
