### ISSUE TITLE
Readme corrections

### ISSUE THREAD

**Issue by shacker** [liamks/pyitunes#35]
The primary "Usage Example" in the readme is broken in several ways.

First: `if song and song.rating > 80:`

At least under Python3.6, this breaks for any song that does not have a rating with 

`TypeError: '>' not supported between instances of 'NoneType' and 'int'`

Can be fixed with:

```
for id, song in l.songs.items():
    if song and song.rating:
        if song.rating > 80:
            print(song.name, song.rating)
```

Second:

`print("[%d] %s - %s" % (song.number, song.artist, song.name))`

According to "Attributes of the Song class" documentation, there is no such attribute as `song.number`, so this fails immediately. If you correct this to:

`print("[%d] %s - %s" % (song.track_number, song.artist, song.name))`

the attribute now exists, but it fails for any tracks missing a track number with:

`TypeError: %d format: a number is required, not NoneType`

This can be fixed (perhaps not gracefully) by changing to 

``print("[%s] %s - %s" % (song.track_number, song.artist, song.name))``

(don't force track_number to be formatted as an int). But now it prints a bunch of "None"s. Could be fixed internally by replacing None with "-" or similar.

Finally, the syntax for string formatting is ancient and  should be updated to use `format()`:

`print("{t} {a} - {n}".format(t=song.track_number, a=song.artist, n=song.name))`

**Comment by liamks** [comment]
Hi @shacker could you submit a PR - I'd be happy to have the Readme updated with these fixes!

**Comment by shacker** [comment]
Done!
