### ISSUE TITLE
Readme should suggest pickling for performance improvements

### ISSUE THREAD

**Issue by shacker** [liamks/pyitunes#36]
With my 98,000 track library, on a very fast Mac, every access through pyitunes takes at least 55 seconds (running the sample code in the readme through `time`). At first I was thinking of forking the project and using some of your code to populate a database and accessing data via the Django or SQLAlchemy ORM. That would have advantages or arbitrary query access, but would be a lot of work. Then realized it would be easier to cache the first access. Python provides `pickle` for this purpose. By pickling,  I was able to reduce each access to around 5 seconds. Not as good as a database, but a huge improvement. Here is a version of the readme that includes fixes from my previous ticket and includes pickling performance improvements with a user-settable cache expiry:

```
import os.path
import pickle
import time
from pyItunes import Library

lib_path = "/Users/[username]/Music/iTunes/iTunes Library.xml"
pickle_file = "itl.p"
expiry = 60 * 60  # Refresh pickled file if older than (in seconds)
epoch_time = int(time.time())  # Now

# Generate pickled version of database if stale or doesn't exist
if not os.path.isfile(pickle_file) or os.path.getmtime(pickle_file) + expiry < epoch_time:
    itl_source = Library(lib_path)
    pickle.dump(itl_source, open(pickle_file, "wb"))

itl = pickle.load(open(pickle_file, "rb"))

print("\nHighly-rated tracks:")
for id, song in itl.songs.items():
    if song and song.rating:
        if song.rating > 80:
            print("{n}, {r}".format(n=song.name, r=song.rating))

print("\nPlaylists:")
playlists = itl.getPlaylistNames()
for playlist in playlists:
    print(playlist)

print("\nTracks in first playlist")
for song in itl.getPlaylist(playlists[0]).tracks:
    print("{t} {a} - {n}".format(t=song.track_number, a=song.artist, n=song.name))
```

**Comment by liamks** [comment]
Instead of using pickle why not keep the file in memory? Sorry I'm trying to understand what Pickle does (e.g. just an in-memory cache?).

**Comment by shacker** [comment]
In-memory only lasts as long as it takes for the script to run. If I need to run the script 10x in a row, or to run 10 different scripts all based on the same data set, as I might do when developing a new feature or who-knows-what-feature, it takes 55 seconds to load the data into memory each time. 

Pickle is python's technology for saving any in-memory object to disk for later retrieval.

**Comment by liamks** [comment]
ahhhhh, makes sense. Thanks for adding this to the readme!
