### ISSUE TITLE
Remove legacymode?

### ISSUE THREAD

**Issue by shacker** [liamks/pyitunes#40]
Just curious how long you want to support legacymode? We could remove a fair bit of clutter without it.

**Comment by liamks** [comment]
Perhaps add something to the readme specifying that version  X  and under support legacy mode, but everything after does not. Thoughts?

**Comment by shacker** [comment]
Agreed. Current version is 1.4. I propose releasing 1.4.1 with the current set of recent changes. Then remove legacy mode and bump version to 1.5 with legacy mode removed. 

Removal of legacy mode could then coincide nicely with move to the new project name and distribution on pypi.

**Comment by liamks** [comment]
Sounds good!

**Comment by shacker** [comment]
Cool. Will you be managing the process of removing legacy and bumping the version and letting Nathan know i #28 that we're ready for PyPi? Or did you want us to do that?

**Comment by liamks** [comment]
Good question. I'd be happy if you guys took over!

**Comment by NathanDotTo** [comment]
Hi

I have started the unit tests, and then become bogged down in trying to create a Library.XML file that works properly. That will just have to wait.

Configuring a Traveis CI build and adding to PyPi can be done when you are ready.

Regards

Nathan
